# Librería Pandas en Python

# Ejemplo 1 - Librería Pandas con serie de datos númericos

In [3]:
import pandas as pd
print('Item Total venta')
s = pd.Series([100.0,200.0,300.0, 500.0,600.0,400.0,700.0,800.0,900.0,1000.0])
s.name='ventas'
print(s)



Item Total venta
0     100.0
1     200.0
2     300.0
3     500.0
4     600.0
5     400.0
6     700.0
7     800.0
8     900.0
9    1000.0
Name: ventas, dtype: float64


# Ejemplo 2 - Pandas con serie de datos y etiquetas de indices tipo string

In [ ]:
import pandas as pd
print('Meses','  Total')
meses = ['enero','febrero','marzo', 'abril','mayo','junio']
totales = [100, 200, 300, 500,600,400]
s = pd.Series(totales, index = meses)
s

Meses   Total


enero      100
febrero    200
marzo      300
abril      500
mayo       600
junio      400
dtype: int64

# Ejemplo 3 - Pandas con serie de datos con diccionario de datos

In [4]:
import pandas as pd
print('Meses','  Total')
dicc = {'enero': 100, 'febrero': 200, 'marzo': 300, 'abril': 500,
       'mayo': 600,'junio': 400,'julio':700}
s = pd.Series(dicc)
s

Meses   Total


enero      100
febrero    200
marzo      300
abril      500
mayo       600
junio      400
julio      700
dtype: int64

# Ejemplo 4 - Atributos y Métodos de una serie de datos

In [5]:
import pandas as pd
print("Items  Totales")
s = pd.Series([100,200,300, 500,600,400])
print(s)
print("Atributos de la Serie de datos")
print("Nombre de la Serie:",s.name)
print("Cantidad de elemento:",str(s.size))
print("Nombres de la filas",s.index)
print("Tipo de dato de los elementos:",s.dtype)
print("Métodos de la Serie de datos")
print("Cantidad de la serie:",str(s.count()))
print("Suma de la serie:",str(s.sum()))
print("Max valor de la serie:",str(s.max()))
print("Min valor de la serie:",str(s.min()))

Items  Totales
0    100
1    200
2    300
3    500
4    600
5    400
dtype: int64
Atributos de la Serie de datos
Nombre de la Serie: None
Cantidad de elemento: 6
Nombres de la filas RangeIndex(start=0, stop=6, step=1)
Tipo de dato de los elementos: int64
Métodos de la Serie de datos
Cantidad de la serie: 6
Suma de la serie: 2100
Max valor de la serie: 600
Min valor de la serie: 100


# Ejemplo 5 -Aplicar operaciones a una serie de datos

In [9]:
import pandas as pd
s = pd.Series([1, 2, 3, 4])
print('producto de la serie')
print(s * 2)
print('nro pares e impares de la serie')
print(s % 2)
print('incrementando caracteres')
ss = pd.Series(['a', 'b', 'c'])
print(ss * 10)

producto de la serie
0    2
1    4
2    6
3    8
dtype: int64
nro pares e impares de la serie
0    1
1    0
2    1
3    0
dtype: int64
incrementando caracteres
0    aaaaaaaaaa
1    bbbbbbbbbb
2    cccccccccc
dtype: object


In [8]:
n=4
r=n%2
print(r)


0


# Ejemplo 6 - Aplicar funciones a una serie de datos

In [18]:
import pandas as pd
U = pd.Series(['a', 'b', 'c','d']).str.upper()
L = pd.Series(['A', 'B', 'C',"D"]).str.lower()
print(U)
print(L)


0    A
1    B
2    C
3    D
dtype: object
0    a
1    b
2    c
3    d
dtype: object


# Ejemplo 7 - Aplicar filtro a la serie de datos

In [25]:
import pandas as pd
print('Item Total venta')
s = pd.Series({'Enero': 100,  'Febrero':200, 'Marzo':300})
# >= , <= , == , != , > , <
print(s[s>=100])

Item Total venta
Enero      100
Febrero    200
Marzo      300
dtype: int64


# Ejemplo 8 - Ordenar los datos de una serie de datos en Pandas.

In [27]:
import pandas as pd
print('Item Total venta')
s = pd.Series({'Enero': 300,  'Febrero':100, 'Abril':200,'Marzo':400})
print(s.sort_index(ascending = True))
print('')
print('Orden de datos descendente')
print(s.sort_index(ascending = False))

Item Total venta
Abril      200
Enero      300
Febrero    100
Marzo      400
dtype: int64

Orden de datos descendente
Marzo      400
Febrero    100
Enero      300
Abril      200
dtype: int64


# Ejemplo 9 - Eliminar los dados desconocidos en una serie de datos con Pandas

In [31]:
import pandas as pd
import numpy as np
print('Item Total venta')
s = pd.Series(['Enero','Febrero',None,'Marzo',np.NaN,'Abril',None])
s.dropna()


Item Total venta


0      Enero
1    Febrero
3      Marzo
5      Abril
dtype: object

# Ejemplo 10 - Utilizar estructura repetitiva FOR con una seria de datos con pandas

In [32]:
import pandas as pd
inicio = int(input('Introduce el año inicial: '))
fin = int(input('Introduce el año final: '))
ventas = {}
for i in range(inicio, fin+1):
    ventas[i] = float(input('Introduce las ventas del año ' + str(i) +': '))
ventas = pd.Series(ventas)
print('Ventas\n', ventas)
print('Ventas con descuento\n', ventas*0.9)

Introduce el año inicial: 2020
Introduce el año final: 2023
Introduce las ventas del año 2020: 100
Introduce las ventas del año 2021: 200
Introduce las ventas del año 2022: 300
Introduce las ventas del año 2023: 400
Ventas
 2020    100.0
2021    200.0
2022    300.0
2023    400.0
dtype: float64
Ventas con descuento
 2020     90.0
2021    180.0
2022    270.0
2023    360.0
dtype: float64


# Ejemplo 11 - Serie de datos con datos estadísticos

In [34]:
import pandas as pd
def estadistica_ventas(ventas):
    v = pd.Series(ventas)
    estadisticos = pd.Series([v.min(), v.max(), v.mean(), v.std()], index=['Min', 'Max', 'Media', 'Desviación Estandar o típica'])
    return estadisticos
ventas ={'Juan':900, 'María':650, 'Pedro':400, 'Carmen': 850, 'Luis': 500}
print('Resultado 1')
print(estadistica_ventas(ventas))
print('\n')
print('Resultado 2')
import pandas as pd
def estadistica_ventas2(ventas):
    v2 = pd.Series(ventas)
    return v2.describe()

ventas ={'Juan':900, 'María':650, 'Pedro':400, 'Carmen': 850, 'Luis': 500}
print(estadistica_ventas2(ventas))


Resultado 1
Min                             400.000000
Max                             900.000000
Media                           660.000000
Desviación Estandar o típica    216.217483
dtype: float64


Resultado 2
count      5.000000
mean     660.000000
std      216.217483
min      400.000000
25%      500.000000
50%      650.000000
75%      850.000000
max      900.000000
dtype: float64


# Ejemplo 12 - Pandas con Serie de datos con funciones de ordenamiento de datos

In [35]:
import pandas as pd

def ventasfiltro(ventas):
    v3 = pd.Series(ventas)
    return v3[v3 >= 500].sort_values(ascending=False)

ventas = {'Juan':300, 'María':650, 'Pedro':400, 'Carmen': 850, 'Luis': 700}
print(ventasfiltro(ventas))

Carmen    850
Luis      700
María     650
dtype: int64


# Ejemplo 13 - DataFrame a partir de un diccionario de listas - 1

In [38]:
import pandas as pd
df=pd.DataFrame({'números':[1,2,3,4,5],'letras':['a','b','c','d','e']})
print(df)
print('Propiedades del Dataframe')
print('dimensión de la matriz:',df.shape)
print("Cantidad de elemento:",str(df.size))


   números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
Propiedades del Dataframe
dimensión de la matriz: (5, 2)
Cantidad de elemento: 10


# Ejemplo 14 - DataFrame a partir de un diccionario de listas - 2

In [41]:
#DataFrame(data =listas, index = filas, columns = columnas, dtype=tipos)
import pandas as pd
lst = [['Juan','Enero',100],['Carla','Febrero',200],['Judith','Marzo',300],['Julio','Abril',400]]
df = pd.DataFrame(lst,index = ['1', '2', '3','4'],columns=['vendedor','mes','total'])
df

vendedor      mes  total
1     Juan    Enero    100
2    Carla  Febrero    200
3   Judith    Marzo    300
4    Julio    Abril    400

# Ejemplo 15 - Dataframe de datos de un diccionario de datos

In [42]:
import pandas as pd
d = {'vendedor':['Juan','Carla','Judith'],
    'mes':["Abril","Mayo","Junio"],
    'total': [500, 400, 600]}
df = pd.DataFrame(d, index = ['id1', 'id2', 'id3'])
df

vendedor    mes  total
id1     Juan  Abril    500
id2    Carla   Mayo    400
id3   Judith  Junio    600

# Ejemplo 16 - Crear un arreglo y matriz de datos con la librería numpy

In [43]:
import numpy as np
#arreglo de datos
print("Arreglo de datos")
arreglo=np.array([1,2,3])
print(arreglo)
print("Matriz de datos")
#matriz de datos
matriz=np.array([[4,5,6],[7,8,9]])
print(matriz)

Arreglo de datos
[1 2 3]
Matriz de datos
[[4 5 6]
 [7 8 9]]


# Ejmeplo 17 - Operaciones con los arreglos y matrices con la librería Numpy

In [44]:
import numpy as np # Importamos numpy como el alias np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])
print('suma de elementos')
print(a + b )
#división de elementos
print('división de elementos')
print(a / b)
#producto de lo elementos
print('producto de elementos')
print(a ** 2)

suma de elementos
[[2 3 4]
 [6 7 8]]
división de elementos
[[1.  2.  3. ]
 [2.  2.5 3. ]]
producto de elementos
[[ 1  4  9]
 [16 25 36]]
