# Introducción a  Numpy

Uno de los módulos más importantes de Python es **[Numpy](http://www.numpy.org/)**.

Numpy es el encargado de añadir toda la capacidad matemática y vectorial a Python haciendo posible operar con cualquier dato numérico o array (posteriormente veremos qué es un array).

## ¿Porqué usar Numpy?

En múltiples ocasiones necesitamos hacer operaciones numéricas sobre datos provenientes de archivos Excel o Bases de datos que contienen múltiples campos (columnas) y múltiples registros (filas).

Vimos que en Python existen las listas, tuplas y diccionarios, las cuales son de gran ayuda para almacenar y administrar datos. Veamos qué sucede cuando queremos sumar los elementos almacenados en dos listas.

In [1]:
x=[1,2,3,4]
y=[5,6,7,8]
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8]


Como podemos notar, el operador + simplemente concatena las dos listas.
Pero ... ¿Cómo haríamos para sumar los elementos de las dos listas, elemento por elemento?

In [3]:
suma=[]
for i in range(4):
    suma.append(x[i]+y[i])

print(suma)

[6, 8, 10, 12]


## Cómo importar el paquete Numpy

Partimos importando el paquete numpy usando la función import. En este caso usaremos el alias np para referirnos de manera más abreviada a las clases y  métodos implementados en numpy.

In [4]:
import numpy as np

## Definición de arreglos en Numpy

In [5]:
# Definir un arreglo 1D

x = np.array([1,2,3,4])
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[1 2 3 4]
type(x):  <class 'numpy.ndarray'>
x.dtype:  int64
x.size:  4
x.shape:  (4,)


In [6]:
# Definir un arreglo 1D con elementos con tipo de dato de punto flotante

x = np.array([1,2,3,4], dtype=np.float32)
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[1. 2. 3. 4.]
type(x):  <class 'numpy.ndarray'>
x.dtype:  float32
x.size:  4
x.shape:  (4,)


In [7]:
# Sumar los arreglos x e y

y = np.array([5,6,7,8])
print('x: ', x)
print('y: ', y)
print('Suma: ', x+y)

x:  [1. 2. 3. 4.]
y:  [5 6 7 8]
Suma:  [ 6.  8. 10. 12.]


In [8]:
# Definir un arreglo 2D

x= np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.size)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
8
(2, 4)


**Cómo funciona el slicing en los arreglos de Numpy**<br />
<img src="images/numpy_indexing.png" width="400">

### Slicing

In [9]:
x[1:]

array([[5, 6, 7, 8]])

In [11]:
x[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [14]:
# Inicializar un arreglo 1D y otro 2D con ceros. Notar que usamos Y por X

x=np.zeros(10)
print('x: ', x)

x:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
# Crear un arreglo usando valores aleatorios entre 0 y 1

x=np.random.random(20)
print(x)

[0.26900693 0.10858173 0.10300859 0.52293113 0.35364472 0.00351263
 0.27976053 0.86167563 0.56332231 0.53648754 0.6740575  0.07016761
 0.78619487 0.25229317 0.21700656 0.08010358 0.67335975 0.45182631
 0.02934956 0.53024364]


In [17]:
# crear un arreglo de enteros aleatorios

y=np.random.randint(0,1000,[3,3])
print(y)

[[416 914 157]
 [491 359 373]
 [773 319 272]]


In [30]:
# matriz identidad
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# matriz diagonal
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [32]:
# Extraer valores de un arreglo Numpy usando indices

x= np.array([[1,2,3,4],
            [5,6,7,8],
             [9,10,11,12]])
print(x)

print('\nx[0,3]: ', x[0,3])

print('\nx[:,0]: ', x[:,0])
print('\nx[0,:]: ', x[0,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,3]:  4

x[:,0]:  [1 5 9]

x[0,:]:  [1 2 3 4]


In [ ]:
x

In [33]:
# Numpy permite crear máscaras fácilmente usando condiciones booleanas
a=x>6
print(a)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [34]:
# Extraer los valores de x que satisfacen la condición booleana. Para ello usamos la máscara
print(x[a])

[ 7  8  9 10 11 12]


In [36]:
x.shape

(3, 4)

In [37]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# Sumar los valores de un arreglo 2D a lo largo del eje Y (columnas)
np.sum(x, axis=0)

array([15, 18, 21, 24])

In [39]:
# Sumar los valores de un arrego 2D a lo largo del eje X (filas)
np.sum(x, axis=1)

array([10, 26, 42])

In [40]:
# Crear la transpuesta de la matriz x
y= x.T
print(y, y.shape)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] (4, 3)


## Funciones matemáticas

In [43]:
x=np.random.random(1000)
#print(x)
print('Media: ', np.mean(x))
print('Desviación Estandar: ', np.std(x))

Media:  0.5128596649984188
Desviación Estandar:  0.28556444561378275


In [23]:
np.random.randn()

0.39551085533186925

In [46]:
# También es posible importar algunas funciones directamente desde las librerías
# Para ello usamos la sintaxis from <nombre_libreria> import <nombre_funcion>
# no quiero llamar asi a mi funcion aleatorio: np.random.random

from numpy.random import random

In [47]:
random(100)

array([3.89006756e-01, 9.39854988e-01, 6.97642829e-01, 6.29871285e-01,
       8.93183069e-04, 4.75517019e-01, 1.97015170e-01, 3.81042394e-01,
       8.80946296e-01, 6.31089436e-01, 2.07908698e-01, 8.86511688e-01,
       8.75764522e-01, 9.74999912e-01, 3.87206414e-01, 2.58059862e-01,
       2.12104177e-01, 4.54548245e-01, 4.75671130e-02, 1.52729167e-01,
       8.02287547e-01, 4.39567382e-03, 9.15729374e-01, 6.34804805e-01,
       6.05346404e-01, 5.68301279e-01, 1.52942497e-01, 9.63294370e-01,
       5.88571297e-02, 4.27429828e-02, 4.99276207e-01, 2.60646758e-01,
       6.76673881e-01, 9.02722033e-01, 2.53764999e-01, 9.07934348e-01,
       5.87285821e-01, 6.67547717e-02, 5.61053087e-01, 6.21569803e-01,
       3.91518959e-03, 3.05416251e-01, 3.41352158e-01, 4.22849380e-01,
       6.70151583e-01, 6.03388151e-01, 4.87330683e-01, 4.66829077e-01,
       7.78878547e-01, 4.08081760e-01, 2.52288442e-01, 8.80153618e-01,
       7.33643011e-01, 1.16447671e-02, 8.27539310e-02, 9.02529103e-01,
      

In [48]:
# Crear un arreglo de enteros que comience en 0 y termine en 10 (no incluído)
x=np.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
# un rango es una lista de numeros consecutivos
y = range(0,10)
print(list(y))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [50]:
# Crear un arreglo de punto flotante que comience en 0 y termine en 10, con paso de 0.5
x=np.arange(0,100,2, dtype=np.int32)
print(x)
print(x.dtype)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
int32


In [51]:
# Usar funciones trigonométricas
# Numpy contiene una serie de constantes matemáticas. Usaremos Pi
print(x[3:8])
x_expo = np.exp(x[3:8])
x_log = np.log(x[3:8])
print(x_expo)
print(x_log)

[ 6  8 10 12 14]
[4.03428793e+02 2.98095799e+03 2.20264658e+04 1.62754791e+05
 1.20260428e+06]
[1.79175947 2.07944154 2.30258509 2.48490665 2.63905733]


In [52]:
x_log10 = np.log10(x[3:8])
print(x_log10)

[0.77815125 0.90308999 1.         1.07918125 1.14612804]


In [54]:
# Usar funciones como potencia
y=np.power(x,2) # elevar cada elemento del arreglo x, a la segunda potencia
print(y)

[   0    4   16   36   64  100  144  196  256  324  400  484  576  676
  784  900 1024 1156 1296 1444 1600 1764 1936 2116 2304 2500 2704 2916
 3136 3364 3600 3844 4096 4356 4624 4900 5184 5476 5776 6084 6400 6724
 7056 7396 7744 8100 8464 8836 9216 9604]


In [55]:
y=np.power(x,5) # elevar cada elemento del arreglo x, a la segunda potencia
print(y)

[          0          32        1024        7776       32768      100000
      248832      537824     1048576     1889568     3200000     5153632
     7962624    11881376    17210368    24300000    33554432    45435424
    60466176    79235168   102400000   130691232   164916224   205962976
   254803968   312500000   380204032   459165024   550731776   656356768
   777600000   916132832  1073741824  1252332576  1453933568  1680700000
  1934917632 -2075960672 -1759441920 -1407792928 -1018167296  -587568864
  -112847872   409302880   982351872  1609932704 -1999119360 -1250894368
  -436207616   449273376]


In [56]:
# Usar funciones como raíz cuadrada
y=np.sqrt(x) # raíz de a, del inglés "square root"
print(y)

[0.         1.41421356 2.         2.44948974 2.82842712 3.16227766
 3.46410162 3.74165739 4.         4.24264069 4.47213595 4.69041576
 4.89897949 5.09901951 5.29150262 5.47722558 5.65685425 5.83095189
 6.         6.164414   6.32455532 6.4807407  6.63324958 6.78232998
 6.92820323 7.07106781 7.21110255 7.34846923 7.48331477 7.61577311
 7.74596669 7.87400787 8.         8.1240384  8.24621125 8.36660027
 8.48528137 8.60232527 8.71779789 8.83176087 8.94427191 9.05538514
 9.16515139 9.2736185  9.38083152 9.48683298 9.59166305 9.69535971
 9.79795897 9.89949494]


Escribir *np.sqrt(x)* es mucho más breve que la alternativa de usar funciones nativas de Python: Calcular una a una las raíces cuadradas de cada elemento de *x*.

In [57]:
y=np.power(x,1/5) # elevar cada elemento del arreglo x, a la segunda potencia
print(y)

[0.         1.14869835 1.31950791 1.43096908 1.51571657 1.58489319
 1.64375183 1.6952182  1.74110113 1.78260246 1.8205642  1.85560074
 1.88817502 1.91864519 1.94729436 1.97435049 2.         2.02439746
 2.04767251 2.06993505 2.09127911 2.11178576 2.13152551 2.15056001
 2.16894354 2.18672415 2.20394458 2.22064303 2.23685383 2.25260788
 2.26793316 2.28285506 2.29739671 2.31157925 2.32542203 2.33894284
 2.35215805 2.36508277 2.37773099 2.39011568 2.40224887 2.41414177
 2.42580483 2.43724782 2.44847985 2.45950949 2.47034475 2.48099318
 2.49146188 2.50175753]
